// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import "@vue/runtime-core";

export {};

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    BarEcharts: typeof import("./src/components/Charts/src/barEcharts.vue")["default"];
    BarEcharts_20230115163152: typeof import("./src/components/Charts/src/barEcharts.vue")["default"];
    BaseEcharts: typeof import("./src/components/Charts/src/baseEcharts.vue")["default"];
    Echarts: typeof import("./src/components/Charts/echarts.vue")["default"];
    ElAside: typeof import("element-plus/es")["ElAside"];
    ElAvatar: typeof import("element-plus/es")["ElAvatar"];
    ElBreadcrumb: typeof import("element-plus/es")["ElBreadcrumb"];
    ElBreadcrumbItem: typeof import("element-plus/es")["ElBreadcrumbItem"];
    ElButton: typeof import("element-plus/es")["ElButton"];
    ElCard: typeof import("element-plus/es")["ElCard"];
    ElCheckbox: typeof import("element-plus/es")["ElCheckbox"];
    ElCol: typeof import("element-plus/es")["ElCol"];
    ElConfigProvider: typeof import("element-plus/es")["ElConfigProvider"];
    ElContainer: typeof import("element-plus/es")["ElContainer"];
    ElDatePicker: typeof import("element-plus/es")["ElDatePicker"];
    ElDialog: typeof import("element-plus/es")["ElDialog"];
    ElDropdown: typeof import("element-plus/es")["ElDropdown"];
    ElDropdownItem: typeof import("element-plus/es")["ElDropdownItem"];
    ElDropdownMenu: typeof import("element-plus/es")["ElDropdownMenu"];
    ElForm: typeof import("element-plus/es")["ElForm"];
    ElFormItem: typeof import("element-plus/es")["ElFormItem"];
    ElHeader: typeof import("element-plus/es")["ElHeader"];
    ElIcon: typeof import("element-plus/es")["ElIcon"];
    ElImage: typeof import("element-plus/es")["ElImage"];
    ElInput: typeof import("element-plus/es")["ElInput"];
    ElLink: typeof import("element-plus/es")["ElLink"];
    ElMain: typeof import("element-plus/es")["ElMain"];
    ElMenu: typeof import("element-plus/es")["ElMenu"];
    ElMenuItem: typeof import("element-plus/es")["ElMenuItem"];
    ElOption: typeof import("element-plus/es")["ElOption"];
    ElPagination: typeof import("element-plus/es")["ElPagination"];
    ElRow: typeof import("element-plus/es")["ElRow"];
    ElSelect: typeof import("element-plus/es")["ElSelect"];
    ElSubMenu: typeof import("element-plus/es")["ElSubMenu"];
    ElTable: typeof import("element-plus/es")["ElTable"];
    ElTableColumn: typeof import("element-plus/es")["ElTableColumn"];
    ElTabPane: typeof import("element-plus/es")["ElTabPane"];
    ElTabs: typeof import("element-plus/es")["ElTabs"];
    ElTooltip: typeof import("element-plus/es")["ElTooltip"];
    HeaderBeard: typeof import("./src/components/Layout/Header/HeaderBeard.vue")["default"];
    HeaderInfo: typeof import("./src/components/Layout/Header/HeaderInfo.vue")["default"];
    HelloWorld: typeof import("./src/components/UerSearch copy/HelloWorld.vue")["default"];
    LineEcharts: typeof import("./src/components/Charts/src/lineEcharts.vue")["default"];
    LoginPanel: typeof import("./src/components/Login/LoginPanel.vue")["default"];
    MapCharts: typeof import("./src/components/Charts/src/mapCharts.vue")["default"];
    NavHeader: typeof import("./src/components/Layout/Header/NavHeader.vue")["default"];
    NavMenu: typeof import("./src/components/Layout/Sidebar/NavMenu.vue")["default"];
    NumberData: typeof import("./src/components/Dashboard/numberData.vue")["default"];
    PageModal: typeof import("./src/components/Page/PageModal.vue")["default"];
    PageSearch: typeof import("./src/components/Page/PageSearch.vue")["default"];
    PageTable: typeof import("./src/components/Page/PageTable.vue")["default"];
    PanelAccount: typeof import("./src/components/Login/PanelAccount.vue")["default"];
    PanelPhone: typeof import("./src/components/Login/PanelPhone.vue")["default"];
    PieEcharts: typeof import("./src/components/Charts/src/pieEcharts.vue")["default"];
    RoseEcharts: typeof import("./src/components/Charts/src/roseEcharts.vue")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
    UserModal: typeof import("./src/components/Page/userModal.vue")["default"];
    UserModal_20230111210605: typeof import("./src/components/UerSearch/userModal.vue")["default"];
    UserSearch: typeof import("./src/components/UerSearch/userSearch.vue")["default"];
    UserSearch_20230111160507: typeof import("./src/components/UerSearch/userSearch_20230111160507.vue")["default"];
    UserTable: typeof import("./src/components/UerSearch/userTable.vue")["default"];
    UserTable_20230112210101: typeof import("./src/components/UerSearch/userTable.vue")["default"];
    WelcomeItem: typeof import("./src/components/UerSearch copy/WelcomeItem.vue")["default"];
    WelcomeItem_20230115191156: typeof import("./src/components/UerSearch/WelcomeItem_20230115191156.vue")["default"];
  }
}
